### ISSUE TITLE
Russian Translation on App Store Page

### ISSUE THREAD

**Issue by purplesyringa** [canewsin/zeronet_mobile_issues#1]
The description translations are weird now (Google Translate I guess?). You might want to copy the descriptions from https://zeronet.io.

**Comment by canewsin** [comment]
@imachug 
Which Language ?

**Comment by canewsin** [comment]
Could you provide a Screenshot, it's asking $14 for 200 words for translation by human on play store, instead I will create translate dir on this repo, so other people can contribute translations.

**Comment by purplesyringa** [comment]
@canewsin Russian for me but I guess it's a problem for all languages. As for the screenshot, I'm not sure what you're asking about, probably the home page on Google Play? Not sure if that would help, it's just the description that I'm talking about.

**Comment by purplesyringa** [comment]
> instead I will create translate dir on this repo, so other people can contribute translations.

Looks great to me.

**Comment by canewsin** [comment]
@imachug You can push ru translation to the repo. See Readme for details.

**Comment by canewsin** [comment]
@imachug thanks for your contribution.
